pluginManagement {
    // The convention plugins that configure this build come from `build-logic`, and there are two
    // ways to get at them. `numverify.buildLogic.source` in gradle.properties picks between them:
    //
    //   includedBuild - `build-logic` is part of this build. Its plugin markers are resolvable by
    //                   every project without a `buildscript { classpath(...) }` block, and edits
    //                   to a convention plugin take effect immediately. The cost is that Gradle
    //                   configures (and up-to-date-checks, or recompiles) that build before this
    //                   one's settings script can resolve a single plugin id.
    //   maven         - the same plugins, resolved from mavenLocal as an ordinary jar published by
    //                   `./gradlew -p build-logic publishToMavenLocal`. The `build-logic` build
    //                   never runs, at the price of having to republish after every change to it.
    //
    // Both paths put the identical jar on the buildscript classpath, so the plugins behave the
    // same either way — see `./benchmark-buildlogic.sh` for what the difference actually costs.
    //
    // These reads see both gradle.properties and `-P` on the command line, which is how the
    // gradle-profiler scenarios flip modes between runs.
    val buildLogicSource = providers.gradleProperty("numverify.buildLogic.source")
        .getOrElse("includedBuild")
    val buildLogicVersion = providers.gradleProperty("numverify.buildLogic.version")
        .getOrElse("0.1.0")

    if (buildLogicSource == "includedBuild") {
        includeBuild("build-logic")
    }

    repositories {
        if (buildLogicSource == "maven") {
            // Scoped to the convention plugins' own group. mavenLocal is a dumping ground, and
            // without the filter a stale locally-installed copy of anything else could shadow the
            // real thing.
            mavenLocal {
                content {
                    includeGroupByRegex("com\\.phundal\\.numverify\\.buildlogic.*")
                }
            }
        }
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }

    if (buildLogicSource == "maven") {
        // One rule rather than a default version for each of the nine ids: it maps every
        // `numverify.*` id straight onto the published jar, whose plugin descriptors (generated by
        // `java-gradle-plugin`) already carry the id -> implementation class mapping.
        resolutionStrategy {
            eachPlugin {
                if (requested.id.id.startsWith("numverify.")) {
                    useModule(
                        "com.phundal.numverify.buildlogic:convention:$buildLogicVersion",
                    )
                }
            }
        }
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Numverify"

include(":app")

// Shared building blocks. Anything usable by more than one feature belongs here.
include(":common:navigation")
include(":common:networking")

// Features. Each is an api/impl/ui triad: `api` is the JVM-only contract other modules compile
// against, `impl` holds implementations nothing else may see, and `ui` renders the screens.
include(":features:numverify:numverify-api")
include(":features:numverify:numverify-impl")
include(":features:numverify:numverify-ui")
