package com.phundal.numverify.buildlogic

import org.gradle.accessors.dm.LibrariesForLibs
import org.gradle.api.Project
import org.gradle.kotlin.dsl.getByType

/**
 * The type-safe `libs` accessors for the consuming build's version catalog, exactly as a build
 * script sees them — `libs.androidx.core.ktx` rather than `findLibrary("androidx-core-ktx")`.
 *
 * [LibrariesForLibs] is generated by Gradle from `gradle/libs.versions.toml`; the `build-logic`
 * build puts the generated classes on this source set's compile classpath (see
 * `convention/build.gradle.kts`) so that a typo or a removed alias fails compilation of the build
 * logic instead of the app build.
 *
 * This reads only the current project's own extensions, which keeps it compatible with isolated
 * projects.
 */
internal val Project.libs: LibrariesForLibs
    get() = extensions.getByType<LibrariesForLibs>()
